### ISSUE TITLE
Nagy a háttérkép

### ISSUE THREAD

**Issue by boapps** [domino-1/irjnekik#1]
Szia!

Először is tetszik a site, köszi érte.

Viszont feltűnt, hogy picit lassan jön be a háttérkép és ránéztem: egy 3MB körüli jpg.

Szerintem minimum egy [tinyjpg](https://tinyjpg.com/)-et lehetne rá dobni, ami különösebb minőségromlés nélkül csökkentené a méretet. De ha szerinted se túl hangsúlyos eleme az oldalnak, akkor ennél drasztikusabb tömörítést is lehetne rajta eszközölni.

(amúgy a másik repo-n nem tudtam issuet nyitni, azért itt írok)

**Comment by domino-1** [comment]
Helló!

Köszi az érdeklődést!! Nagyon későn láttam csak ezt, de megvan. (Nem tudom most már mennyit számít de tényleg jobb így) 😆
